[package]
name = "fasttime"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastly-shared = "0.5"
anyhow = "1.0"
log = "0.4"
wasmtime = "0.21.0"
wasmtime-wasi = "0.21.0"
structopt = "0.3.15"
pretty_env_logger = "0.4.0"
byteorder = "1.3.4"
hyper = "0.13"
# todo: upgrade to 0.3 https://tokio.rs/blog/2020-10-tokio-0-3
# this may require minor compat shims with hyper 0.13
tokio = { version = "0.2", features = ["macros"] }
